# Generated by Django 5.0.7 on 2024-09-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_rename_timestamp_status_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
    ]
